### ISSUE TITLE
property chains not working?

### ISSUE THREAD

**Issue by cmungall** [balhoff/arachne#4]
no inference:

![image](https://cloud.githubusercontent.com/assets/50745/26382788/b76c86da-3fe3-11e7-9279-9bb8c356b20d.png)

inference:

![image](https://cloud.githubusercontent.com/assets/50745/26382800/cb83d4c0-3fe3-11e7-80a6-504618e50944.png)

inference: 

![image](https://cloud.githubusercontent.com/assets/50745/26382847/3323fa7e-3fe4-11e7-9285-e2cc6a3cf727.png)

This could be a minerva config issue, but I'm pretty sure all of RO is loaded, and we have the axiom MC-part part-of some MC.

Could it be that TBox property chains aren't recognized (the 3rd example shows that ABox property chains are)

**Comment by balhoff** [comment]
Quick answer for now, yes, it's a limitation from OWL RL unfortunately. If this situation is too common then we will need some combination of RL and EL.

**Comment by balhoff** [comment]
https://www.w3.org/TR/2012/REC-owl2-profiles-20121211/#Feature_Overview_3

**Comment by balhoff** [comment]
@dosumis this is an aspect of OWL RL to be aware of.

**Comment by dosumis** [comment]
If I understand correctly:  property chain conversion to rules => use inference in the third case from the facts/OPAs in the lego model.  But the first case doesn't work because the rules won't give equivalent inference across quantified assertions in the ontology (as property chains would).  Is this correct?

**Comment by balhoff** [comment]
Basically, someValuesFrom in equivalentClass definitions will drive classification of individuals. someValuesFrom in superclass position are not handled by an RL reasoner. So the part of the chain that involves an unknown individual in this case doesn't lead to the desired classification. RL generally excludes aspects of OWL which require consideration of unknown individuals. However we still use some of this info because we precompute the EL class hierarchy: any inferred subClaasOf relations between named classes are of course then used in the RL reasoning.

**Comment by balhoff** [comment]
Anyway, I just repeated what you said. Yes, that's right. :-)

**Comment by balhoff** [comment]
I'm going to close this because I think things are working correctly from the perspective of OWL RL. If needed we could separately explore other strategies for reasoning completeness in the GO context, which might involve alternate application of Arachne and ELK.
